export interface StoreActivityReportRow {
  id: string;
  occurredAt: string;
  direction: "IN" | "OUT";
  quantity: string | number;
  balanceAfter?: string | number | null;
  documentType: string;
  documentId: string;
  requisitionNumber?: string | null;
  product?: { name: string; sku: string };
  bin?: { code: string; name: string };
  uom?: { code: string };
  performedBy?: { fullName: string };
}

const safe = (value: unknown) =>
  String(value ?? "-").replace(/[&<>"']/g, (char) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;",
  })[char]!);

export function printStoreActivityReport(
  store: { code: string; name: string; storeType: string },
  rows: StoreActivityReportRow[],
  filterText: string,
) {
  const popup = window.open("", "_blank", "width=1180,height=820");
  if (!popup) return false;
  const logo = new URL("/Inventory_Logo.png", window.location.origin).href;
  const body = rows.map((row, index) => `<tr>
    <td class="center">${index + 1}</td>
    <td><b>${safe(row.product?.name)}</b><small>${safe(row.product?.sku)}</small></td>
    <td><b>${safe(row.requisitionNumber)}</b></td>
    <td><span class="direction ${row.direction.toLowerCase()}">${row.direction}</span></td>
    <td>${new Date(row.occurredAt).toLocaleString("en-GB")}</td>
    <td>${safe(row.bin?.code)}<small>${safe(row.bin?.name)}</small></td>
    <td class="num"><b>${Number(row.quantity).toLocaleString()}</b> ${safe(row.uom?.code)}</td>
    <td class="num">${row.balanceAfter == null ? "-" : Number(row.balanceAfter).toLocaleString() + " " + safe(row.uom?.code)}</td>
  </tr>`).join("");
  popup.document.write(`<!doctype html><html><head><title>${safe(store.name)} Activity</title><style>
  @page{size:A4 landscape;margin:9mm}*{box-sizing:border-box}body{margin:0;background:#eef5f0;color:#18271f;font:10px Arial,sans-serif;print-color-adjust:exact;-webkit-print-color-adjust:exact}.report{max-width:1120px;margin:16px auto;background:#fff;border:1px solid #d7e2da;border-radius:18px;overflow:hidden;box-shadow:0 14px 40px #163d2d22}.hero{display:flex;justify-content:space-between;align-items:center;padding:19px 25px;color:#fff;background:linear-gradient(120deg,#0b4636,#176146 62%,#8bbb3f)}.brand{display:flex;align-items:center;gap:12px}.logo{width:60px;height:60px;border-radius:13px;background:#fff;padding:4px;object-fit:contain}.brand b{display:block;font-size:20px}.brand span,.title p{color:#d9f1e4;font-size:8px;letter-spacing:.14em;text-transform:uppercase}.title{text-align:right}.title h1{margin:0;font-size:22px}.title p{margin:5px 0 0}.meta{display:grid;grid-template-columns:repeat(4,1fr);background:#f8fbf7;border-bottom:1px solid #d7e2da}.meta div{padding:11px 16px;border-right:1px solid #d7e2da}.meta div:last-child{border:0}.label{display:block;color:#71877b;font-size:8px;font-weight:700;text-transform:uppercase}.meta b{display:block;margin-top:4px}.content{padding:17px 19px}table{width:100%;border:1px solid #d5e1d8;border-collapse:separate;border-spacing:0;border-radius:10px;overflow:hidden}th{padding:8px;background:#eaf2eb;color:#315b49;font-size:7px;text-align:left;text-transform:uppercase}td{padding:7px 8px;border-top:1px solid #e5ebe6}tbody tr:nth-child(even){background:#fafcf9}.num{text-align:right!important}.center{text-align:center!important}small{display:block;margin-top:2px;color:#71877b}.direction{display:inline-block;border-radius:999px;padding:3px 8px;font-weight:800}.in{background:#e7f5ec;color:#167047}.out{background:#fff1df;color:#a6550b}.foot{padding:9px;text-align:center;background:#f3f7f2;color:#7b8d83;font-size:8px}@media print{body{background:#fff}.report{margin:0;box-shadow:none}}
  </style></head><body><main class="report"><header class="hero"><div class="brand"><img class="logo" src="${logo}" alt="FeedTrack"><div><b>FeedTrack</b><span>Production Inventory</span></div></div><div class="title"><h1>Store Activity Report</h1><p>${safe(store.code)} - ${safe(store.name)}</p></div></header><section class="meta"><div><span class="label">Store</span><b>${safe(store.code)} - ${safe(store.name)}</b></div><div><span class="label">Store Type</span><b>${safe(store.storeType.replace("_", " "))}</b></div><div><span class="label">Records</span><b>${rows.length}</b></div><div><span class="label">Filters</span><b>${safe(filterText || "All activity")}</b></div></section><section class="content"><table><thead><tr><th class="center">#</th><th>Product</th><th>Requisition ID</th><th>In / Out</th><th>Date & Time</th><th>Bin</th><th class="num">Quantity</th><th class="num">Balance After</th></tr></thead><tbody>${body || '<tr><td colspan="8" class="center">No activity found.</td></tr>'}</tbody></table></section><footer class="foot">Generated by FeedTrack Production Inventory on ${new Date().toLocaleString("en-GB")}</footer></main><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);
  popup.document.close();
  return true;
}
