import { Router } from "express";
import bcrypt from "bcryptjs";
import { z } from "zod";
import { prisma } from "../prisma.js";
import { requirePermission } from "./rbac.js";
export const usersRouter=Router();
usersRouter.use(requirePermission("users.manage"));
usersRouter.get("/",async(req,res)=>{const isSuper=req.auth!.isSuperAdmin;const orgIds=isSuper?undefined:req.auth!.organizations.map(o=>o.id);const members=await prisma.organizationMember.findMany({where:orgIds?{organizationId:{in:orgIds}}:{},include:{user:true,organization:true,role:true},orderBy:{user:{fullName:"asc"}}});res.json({data:members.map(m=>({id:m.user.id,membershipId:m.id,email:m.user.email,fullName:m.user.fullName,isActive:m.isActive,organization:{id:m.organization.id,name:m.organization.name},role:{id:m.role.id,code:m.role.code,name:m.role.name}}))});});
usersRouter.get("/roles",async(req,res)=>res.json({data:await prisma.role.findMany({where:req.auth!.isSuperAdmin?{}:{code:{notIn:["SUPER_ADMIN","ADMIN"]}},include:{permissions:{include:{permission:true}}},orderBy:{name:"asc"}})}));
usersRouter.get("/permissions",requirePermission("roles.manage"),async(_req,res)=>res.json({data:await prisma.permission.findMany({orderBy:{key:"asc"}})}));
usersRouter.post("/",async(req,res)=>{
  const body=z.object({email:z.string().trim().email(),fullName:z.string().trim().min(2).max(100),password:z.string().min(8).max(128),organizationIds:z.array(z.string().uuid()).min(1),roleId:z.string().uuid()}).parse(req.body);
  const organizationIds=[...new Set(body.organizationIds)];
  if(!req.auth!.isSuperAdmin&&!organizationIds.every(id=>req.auth!.organizations.some(organization=>organization.id===id)))return res.status(403).json({error:{message:"Admins can only assign their organizations"}});
  const [role,organizationCount,existingUser]=await Promise.all([prisma.role.findUnique({where:{id:body.roleId}}),prisma.organization.count({where:{id:{in:organizationIds},isActive:true}}),prisma.user.findUnique({where:{email:body.email.toLowerCase()}})]);
  if(!role)return res.status(400).json({error:{message:"Role not found"}});
  if(organizationCount!==organizationIds.length)return res.status(400).json({error:{message:"One or more organizations are invalid"}});
  if(existingUser)return res.status(409).json({error:{code:"EMAIL_IN_USE",message:"A user with this email already exists"}});
  if(!req.auth!.isSuperAdmin&&["SUPER_ADMIN","ADMIN"].includes(role.code))return res.status(403).json({error:{message:"Only Super Admin can assign Admin roles"}});
  const user=await prisma.$transaction(async tx=>{
    const created=await tx.user.create({data:{email:body.email.toLowerCase(),fullName:body.fullName,passwordHash:await bcrypt.hash(body.password,12)}});
    await tx.organizationMember.createMany({data:organizationIds.map(organizationId=>({userId:created.id,organizationId,roleId:role.id}))});
    return created;
  });
  return res.status(201).json({data:{id:user.id}});
});
usersRouter.put("/:userId/assignments",async(req,res)=>{if(!req.auth!.isSuperAdmin)return res.status(403).json({error:{message:"Only Super Admin can change organization assignments"}});const body=z.object({organizationIds:z.array(z.string().uuid()).min(1),roleId:z.string().uuid()}).parse(req.body);const organizationIds=[...new Set(body.organizationIds)];const [user,role,organizationCount]=await Promise.all([prisma.user.findUnique({where:{id:req.params.userId}}),prisma.role.findUnique({where:{id:body.roleId}}),prisma.organization.count({where:{id:{in:organizationIds},isActive:true}})]);if(!user)return res.status(404).json({error:{message:"User not found"}});if(!role)return res.status(400).json({error:{message:"Role not found"}});if(organizationCount!==organizationIds.length)return res.status(400).json({error:{message:"One or more organizations are invalid"}});await prisma.$transaction(async tx=>{await tx.organizationMember.deleteMany({where:{userId:user.id,organizationId:{notIn:organizationIds}}});for(const organizationId of organizationIds)await tx.organizationMember.upsert({where:{userId_organizationId:{userId:user.id,organizationId}},update:{roleId:role.id,isActive:true},create:{userId:user.id,organizationId,roleId:role.id}});});res.status(204).end();});
usersRouter.delete("/:membershipId",async(req,res)=>{const membership=await prisma.organizationMember.findUnique({where:{id:req.params.membershipId},include:{role:true}});if(!membership)return res.status(404).json({error:{message:"Organization access not found"}});if(membership.userId===req.auth!.id)return res.status(400).json({error:{message:"You cannot remove your own access"}});if(!req.auth!.isSuperAdmin&&!req.auth!.organizations.some(o=>o.id===membership.organizationId))return res.status(403).json({error:{message:"Not allowed for this organization"}});if(membership.role.code==="SUPER_ADMIN"&&!req.auth!.isSuperAdmin)return res.status(403).json({error:{message:"Only Super Admin can remove Super Admin access"}});await prisma.organizationMember.delete({where:{id:membership.id}});res.status(204).end();});
usersRouter.patch("/:membershipId",async(req,res)=>{const body=z.object({roleId:z.string().uuid().optional(),isActive:z.boolean().optional(),overrides:z.array(z.object({permissionId:z.string().uuid(),granted:z.boolean()})).optional()}).parse(req.body);const membership=await prisma.organizationMember.findUniqueOrThrow({where:{id:req.params.membershipId},include:{role:true}});if(!req.auth!.isSuperAdmin&&!req.auth!.organizations.some(o=>o.id===membership.organizationId))return res.status(403).json({error:{message:"Not allowed for this organization"}});if(body.roleId){const role=await prisma.role.findUniqueOrThrow({where:{id:body.roleId}});if(!req.auth!.isSuperAdmin&&["SUPER_ADMIN","ADMIN"].includes(role.code))return res.status(403).json({error:{message:"Only Super Admin can assign Admin roles"}});}await prisma.organizationMember.update({where:{id:membership.id},data:{roleId:body.roleId,isActive:body.isActive}});if(body.overrides&&req.auth!.isSuperAdmin)for(const o of body.overrides)await prisma.userPermissionOverride.upsert({where:{membershipId_permissionId:{membershipId:membership.id,permissionId:o.permissionId}},update:{granted:o.granted},create:{membershipId:membership.id,permissionId:o.permissionId,granted:o.granted}});res.status(204).end();});
