import { useEffect,useState } from "react";
import { BadgeDollarSign,Pencil,Plus,Search,Trash2 } from "lucide-react";
import { api,selectedOrg } from "../../../shared/api/http";
import { usePageLoading } from "../../../shared/hooks/usePageLoading";
import { PageContainer } from "../../../components/ui/PageContainer";
import { Card } from "../../../components/ui/Card";
import { DataTable } from "../../../components/ui/DataTable";
import { Button } from "../../../components/ui/Button";
import { Input } from "../../../components/ui/Input";
import { FormField } from "../../../components/ui/FormField";
import { Modal } from "../../../components/ui/Modal";
import { ConfirmationModal } from "../../../components/ui/ConfirmationModal";
import { useToastMessage } from "../../../components/ui/Toast";
interface Currency{id:string;code:string;name:string;symbol:string;decimalPlaces:number}
const blank={code:"",name:"",symbol:"",decimalPlaces:"2"};
export function CurrenciesPage(){const[loading,runLoad]=usePageLoading(),[rows,setRows]=useState<Currency[]>([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<Currency|null>(null),[target,setTarget]=useState<Currency|null>(null),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(false),[form,setForm]=useState(blank),[,toast]=useToastMessage();
const load=()=>runLoad(async()=>{if(!selectedOrg())return toast("Select an organisation first.");try{setRows((await api<{data:Currency[]}>("/currencies")).data)}catch(e:any){toast(e.message)}});
useEffect(()=>{void load()},[]);
const submit=async()=>{if(saving)return;setSaving(true);try{await api(editing?"/currencies/"+editing.id:"/currencies",{method:editing?"PUT":"POST",body:JSON.stringify({...form,decimalPlaces:Number(form.decimalPlaces)})});setOpen(false);setEditing(null);await load()}catch(e:any){toast(e.message)}finally{setSaving(false)}};
const remove=async()=>{if(!target||deleting)return;setDeleting(true);try{await api("/currencies/"+target.id,{method:"DELETE"});setTarget(null);await load()}catch(e:any){toast(e.message)}finally{setDeleting(false)}};
const filtered=rows.filter(x=>[x.code,x.name,x.symbol].some(v=>v.toLowerCase().includes(search.toLowerCase())));
return <PageContainer loading={loading} cap="MASTER SETUP" title="Currency" description="Define currencies used for product prices." actions={<Button variant="primary" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Plus size={16}/>New Currency</Button>}><Card padding="none"><div className="flex items-center justify-between gap-3 border-b border-[#e0e5dd] p-5"><h2 className="font-semibold">Currency List</h2><div className="flex w-72 items-center gap-2 rounded-lg border bg-[#f8faf7] px-3"><Search size={15}/><input className="h-10 w-full bg-transparent text-sm outline-none" placeholder="Search currencies..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div><DataTable columns={["Code","Currency Name","Symbol","Decimal Places","Actions"]} empty={<div className="grid min-h-56 place-items-center text-center"><div><BadgeDollarSign className="mx-auto mb-3 text-[#7a9185]"/><b>No currencies found</b></div></div>}>{filtered.map(x=><tr key={x.id}><td className="font-mono font-semibold">{x.code}</td><td>{x.name}</td><td>{x.symbol}</td><td>{x.decimalPlaces}</td><td><div className="flex gap-2"><Button className="size-9 min-h-9 p-0" aria-label={"Edit "+x.name} onClick={()=>{setEditing(x);setForm({code:x.code,name:x.name,symbol:x.symbol,decimalPlaces:String(x.decimalPlaces)});setOpen(true)}}><Pencil size={15}/></Button><Button className="size-9 min-h-9 p-0 text-red-600" aria-label={"Delete "+x.name} onClick={()=>setTarget(x)}><Trash2 size={15}/></Button></div></td></tr>)}</DataTable></Card>
{target&&<ConfirmationModal title="Delete currency?" confirmLabel="Delete Currency" pending={deleting} onCancel={()=>setTarget(null)} onConfirm={()=>void remove()}>Delete <strong>{target.name} ({target.code})</strong>?</ConfirmationModal>}
{open&&<Modal title={editing?"Edit Currency":"New Currency"} description="Enter the currency details used for product pricing." onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="primary" disabled={saving||form.code.trim().length!==3||!form.name.trim()||!form.symbol.trim()} onClick={()=>void submit()}>{saving?"Saving...":editing?"Save Changes":"Create Currency"}</Button></>}><div className="grid grid-cols-2 gap-4 max-[640px]:grid-cols-1"><FormField label="ISO Code" required><Input maxLength={3} placeholder="BDT" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></FormField><FormField label="Currency Name" required><Input placeholder="Bangladeshi Taka" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></FormField><FormField label="Symbol" required><Input placeholder="Tk" value={form.symbol} onChange={e=>setForm({...form,symbol:e.target.value})}/></FormField><FormField label="Decimal Places"><Input type="number" min="0" max="4" value={form.decimalPlaces} onChange={e=>setForm({...form,decimalPlaces:e.target.value})}/></FormField></div></Modal>}</PageContainer>}